[rospy.client][INFO] 2021-12-10 08:35:55,294: init_node, name[/server_endpoint], pid[8561]
[xmlrpc][INFO] 2021-12-10 08:35:55,294: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-10 08:35:55,294: Started XML-RPC server [http://wng:37763/]
[rospy.init][INFO] 2021-12-10 08:35:55,294: ROS Slave URI: [http://wng:37763/]
[rospy.impl.masterslave][INFO] 2021-12-10 08:35:55,294: _ready: http://wng:37763/
[xmlrpc][INFO] 2021-12-10 08:35:55,295: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-10 08:35:55,295: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-12-10 08:35:55,395: registered with master
[rospy.rosout][INFO] 2021-12-10 08:35:55,395: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-10 08:35:55,396: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-10 08:35:55,396: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-10 08:35:55,401: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-10 08:35:55,531: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-10 08:35:56,594: Connection from 192.168.0.8
[rosout][INFO] 2021-12-10 08:35:56,600: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-10 08:35:56,674: topic[/execution_check] adding connection to [http://wng:37763/], count 0
[rospy.internal][INFO] 2021-12-10 08:35:56,675: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-12-10 08:51:55,289: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-10 08:51:55,296: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-10 08:51:55,296: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-10 08:51:55,296: topic[/execution_check] removing connection to http://wng:37763/
[rospy.impl.masterslave][INFO] 2021-12-10 08:51:55,297: signal-2
[rospy.internal][WARNING] 2021-12-10 08:51:55,298: Unknown error initiating TCP/IP socket to wng:38059 (http://wng:37763/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 561, in connect
    self.write_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 642, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 417, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[rospy.core][INFO] 2021-12-10 08:51:55,404: signal_shutdown [atexit]
